### ISSUE TITLE
Changing focus

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/tui-go#1]
User need to be able to change focus from one widget to another, e.g. between OK and Cancel buttons.

tui should be able to construct a default focus chain that can be overrided.

Cycling widgets should probably be done with Tab and Shift-Tab.

**Comment by november-eleven** [comment]
If you could catch mouse input (if available) in order to gain focus, or other similar stuff, it would be really appreciated.

**Comment by marcusolsson** [comment]
Mouse support is definitely something I'd like to look into. I've tried a couple of approaches for focus events but none that I've been happy about. I'll make sure to consider mouse support in the next iteration.

**Comment by marcusolsson** [comment]
Random though; In GUI applications, the Tab/Shift-Tab way is pretty standard, but I'm not convinced I want to adopt it as a opinionated focus strategy. Compare with vim or emacs that use key combinations for switching buffers.

**Comment by egonelbre** [comment]
There's also up/down, left/right, page up/down, home/end... where the behavior, can vary from widget to widget... + shortcuts.

**Comment by marcusolsson** [comment]
Right, there's just too many variants to choose from. I'm thinking of leaving the means of interaction entirely to the user and only providing something like (pseudo code-ish):

```
func SetFocusChain(chain ...Widget) { ... }

type Chain []Widget
chain.FocusNext()
chain.FocusPrev()
```

... that only takes care of sending the appropriate focus events.

**Comment by egonelbre** [comment]
The appropriate place to focus can change dynamically.

E.g. if you can auto-fill address based on the zip code, you could skip those fields. Similarly, the focus order forward/backward are not necessarily the same (this is a rarer case, e.g. you skipped the address field, but need to make a minor edit to it).

I would most likely use some tab-order + allow explicit modification of focus. Of course the chain approach could work as well... although custom handling would be more difficult... one additional approach would be to allow "complete custom handling" with something like `type FocusHandler struct { Next(w Widget) Widget }` at the cost of making the API more complicated.

_PS: I'm not saying that you should handle all those cases; do what makes more sense for this library... Usually adding extendability adds complexity._

**Comment by marcusolsson** [comment]
Valid points indeed! I'm working on improving layout management for now, and probably won't look seriously into this for a while. If anyone's interested in giving it a shot, I'd be happy to accept a pull request :)

**Comment by marcusolsson** [comment]
I've added initial support for changing focus. Check out the `http` and `login` examples. Ideally, a default focus chain should be provided that changes focus in the order the widgets where added to the layout. Meanwhile, introducing a `FocusChain` interface should allow users to implement similar functionality themselves.

**Comment by egonelbre** [comment]
Shift - Tab is usually used for walking the focus in reverse order.

**Comment by marcusolsson** [comment]
You're totally right about that, and indeed it was my initial approach. Unfortunately - and this was new to me - terminals generally are not able to provide information on which modifier that was pressed. Meaning tcell can't tell me if Shift+Tab was pressed. From the tcell documentation:

> For example, if the rune is 'A', this will be reported without the ModShift bit set, since really can't tell if the Shift key was pressed (it might have been CAPSLOCK, or a terminal that only can send capitals, or keyboard with separate capital letters from lower case letters).

Not sure what the best way forward would be. Ctrl seems to work, so maybe have Ctrl+Tab do reverse focusing, despite not being intuitive.

**Comment by egonelbre** [comment]
On windows you can get all the details you need (https://gist.github.com/egonelbre/609a4e3f64dc50c4707207e8aed60ac6).

On linux you usually get a backtab sequence (you can test with `showkey -a` to see the raw input).

For more information: https://stuff.mit.edu/afs/sipb/user/daveg/Info/backtab-howto.txt

**Comment by marcusolsson** [comment]
Thanks for the resources! Ideally, I think this is something that should be handled in tcell. I will make sure to look into the options before this issue can be closed.

**Comment by marcusolsson** [comment]
Found this commit: https://github.com/zyedidia/micro/commit/c409f1cc07f5c0e4b6e9766ab9bb10f1ebd92015

> I was under the impression that tcell couldn't detect shift tab
key presses, but this was incorrect. It turns out that tcell just
calls it backtab.

I'm guilty of the same impression :) Looking closer, indeed there is a `tcell.Backtab` in tcell. Will have a look at it later today!

**Comment by marcusolsson** [comment]
`tcell.Backtab` is now default for reversing focus order
