### ISSUE TITLE
Multi line Entry

### ISSUE THREAD

**Issue by Danik32** [marcusolsson/tui-go#10]
Enhancement request:
A multi line version of Entry would be really nice.

**Comment by marcusolsson** [comment]
Definitely! I'll look into improving text entry (single and multi-line) in the coming days.

**Comment by marcusolsson** [comment]
I've added a TextEdit that should handle multi-line text input. Check out the new `editor` example for how it can be used.

**Comment by Danik32** [comment]
Nice!
