### ISSUE TITLE
Box, new backgound fill, and SetStyleName

### ISSUE THREAD

**Issue by lrstanley** [marcusolsson/tui-go#106]
With the changes in PR https://github.com/marcusolsson/tui-go/pull/89 (re: https://github.com/marcusolsson/tui-go/issues/60, and https://github.com/marcusolsson/tui-go/issues/45), this makes it so we can style boxes (which is nice!), however there is still an issue of that this can only be set globally across the entire theme. Unless I'm mistaken, since Box doesn't support using `SetStyleName()`, it cannot be designated per-box, in the theme.

The parent library, tcell, has an example referenced application as shown below, which shows what I am attempting to accomplish:
![](http://2.bp.blogspot.com/--OsvnfzSNow/Vf7aqMw3zXI/AAAAAAAAARo/uOMtOvw4Sbg/s1600/Screen%2BShot%2B2015-09-20%2Bat%2B9.08.41%2BAM.png)

With the current way themes work (I know styling is very much in flux), we can't set a background for Spacers, and we cannot set a background for a single Box. This means the example 'keybind' grey bar at the bottom of the above screenshot isn't possible (amongst other things). If I try, I set the entire background of the TUI, since it's constructed using a VBox.

Are there plans to add `SetStyleName` to the Box type? or is there another way of doing this that I am missing?

The temporary solution is to just add a label at the end, with a few hundred repeated whitespaces, and set the backgound to that.. which is far from clean.

**Comment by cceckman** [comment]
The pattern I've used for styling particular elements is to embed the `Widget`:

```golang
type StyledElement struct {
  tui.Widget
}

func (d *Draw) Draw(p *tui.Painter) {
  p.WithStyle("my custom style", d.Widget.Draw)
}
```

(Most of the widgets I have aren't just `tui` widgets, but widgets embedded in other things, so this has worked for me so far. :-/ )


More extensive thoughts on `SetStyleName` as a sufficient-or-desirable API in #74.

**Comment by cceckman** [comment]
To be clear - I agree that this could be easier to deal with :-) But if you want to keep moving, embedding is an option available right now.

**Comment by lrstanley** [comment]
:+1: Didn't know I could do that. I'll check it out, thanks for the suggestion. If that does end up working (which it sounds like it will), I'll close this and wait for followup in #74. I've been watching the issue for some time. Getting anxious, given termui's lack of merging of PR's/updates.

**Comment by lrstanley** [comment]
```go
type styledElement struct {
	name string
	tui.Widget
}

func (w *styledElement) Draw(p *tui.Painter) {
	p.WithStyle(w.name, w.Widget.Draw)
}
```

```go
&styledElement{"my-custom-style", tui.NewHBox(elements...)}
```

Works well. Thanks! Closing out and will continue to watch for updates on the potential style API improvements.
