### ISSUE TITLE
Password mode for Entry

### ISSUE THREAD

**Issue by tflolo** [marcusolsson/tui-go#107]
In case of the login example, can we replace the password with asterisk i.e **** or not draw any text in the entry?

**Comment by marcusolsson** [comment]
I think we could support both asterisks as well as no output. Something like:

```
type EchoMode int

const (
    Normal EchoMode = iota
    NoEcho
    Password
)

func (e *Entry) SetEchoMode(m EchoMode) {
    // ...
}
```
