### ISSUE TITLE
Tui-go crashes when run in a terminal that is too small.

### ISSUE THREAD

**Issue by Danik32** [marcusolsson/tui-go#11]
Returns "panic: Parameter is incorrect." Probably passing incorrect values to termbox again.
Offtopic: Found it while playing around with resizing the terminal. Your library really handles it well :D

**Comment by marcusolsson** [comment]
Could you see if this one goes away with the latest commit as well?

**Comment by Danik32** [comment]
The issue is fixed in the default examples. Though it still remains in my code (I haven't completely updated it to the new doc yet)
