### ISSUE TITLE
 Proposal: Execution of commands

### ISSUE THREAD

**Issue by d3nw0** [marcusolsson/tui-go#116]
Basically, I would like to execute a command such as `vim command.go` and then have it on a separate view, that I could switch by setting the ui widget to this `ui.SetWidget(commandWidget)`.

Hopefully that wouldn't be hard to implement.

**Comment by cceckman** [comment]
I think you're asking for a terminal emulator/capture widget? E.g. the thing underlying `tmux` / `screen`?

From what I understand of terminal emulators, it's very nontrivial to implement. (Unless someone has already done it in Go, in which case :-) )

**Comment by marcusolsson** [comment]
I think @cceckman is correct here. This is a fairly complex thing to implement and while I think it's a cool idea, I don't think this will happen anytime soon. I'm going ahead and closing this for now.
