### ISSUE TITLE
Force redrawing

### ISSUE THREAD

**Issue by gchaincl** [marcusolsson/tui-go#119]
I'm building a tool which needs to update widget content based on foreign events (data from socket) and I couldn't find a way to redraw the widget, I need to wait until the user press a key to reflect the change.
Is there a way to do this?

**Comment by marcusolsson** [comment]
Yes, check the `audioplayer` example to see how to use the `Update` method: https://github.com/marcusolsson/tui-go/blob/master/example/audioplayer/main.go#L65-L70

Be careful not to call Update from the UI goroutine though, since it will cause a deadlock at the moment.

**Comment by gchaincl** [comment]
Great thanks!
