### ISSUE TITLE
Cross compilation to ARMv7 fails

### ISSUE THREAD

**Issue by lamg** [marcusolsson/tui-go#120]
The command `env GOARCH=arm GOARM=7 go build` gives the output
```
# github.com/marcusolsson/tui-go
../../../../marcusolsson/tui-go/box.go:332:7: constant 9223372036854775807 overflows int
```
I'm using go1.9.2 linux/amd64

**Comment by marcusolsson** [comment]
@lamg Hopefully fixed. Let me know if this is still an issue! Thanks for reporting!
