### ISSUE TITLE
align text in widget

### ISSUE THREAD

**Issue by dedalqq** [marcusolsson/tui-go#127]
Hello.
Are there any ways to implement a text alignment in Widget?
I need the "right alignment"
Example:

```
┌─────────────────────┐
│..................foo│
└─────────────────────┘
```

Thank you!

**Comment by dedalqq** [comment]
I found a solution, I can use `NewSpacer()`

```
tui.NewHBox(tui.NewSpacer(), tui.NewLabel("foo")),
```

Is this really the best solution, or is there something more best?

**Comment by lrstanley** [comment]
That's going to be the most idiomatic way of doing it, at least that I know of.

**Comment by marcusolsson** [comment]
@dedalqq I'd agree with @lrstanley that this the best way to accomplish this for now 👍

**Comment by dedalqq** [comment]
Thank you =)
