### ISSUE TITLE
Allow for removing a single item from a list

### ISSUE THREAD

**Issue by dougreese** [marcusolsson/tui-go#13]
List items can be added but not removed.  Since the items are a simple `[]string` a `Clear()` method  would be a fairly straight forward approach, knowing items will have to be re-added if only one item is being cleared.

**Comment by marcusolsson** [comment]
Definitely! I could easily see a `RemoveItem(i int)` for removing a specific item, which I think would be more versatile than removing all items and then re-adding them. If you really want to remove all items, it should be simple enough for users to write the loop themselves (in an effort to keep the API small). Then we would need to add a `Len`/`NumItems`/`Count` method to return number of items, which I think makes sense as well.

If you need this ASAP, I'll have it done by tomorrow. Ideally though, I'd like to leave this issue available as easy picking for anyone who wants to contribute.

**Comment by dougreese** [comment]
I added a `RemoveAll()` which was easy allows me to move forward.  I will change it to a `RemoveItem()` call and submit a PR, which closely resembles the JS Select control.  

However, Qt collections and some widgets have a `Clear()` and/or `RemoveAll()` method.

**Comment by marcusolsson** [comment]
I'd be happy to accept your PR! 

(I'm with you on the `RemoveAll`. Currently, though I'm trying to slim down and stabilize the API for (hopefully) an initial release. I'd be open to adding a `RemoveAll` method in the future.)

**Comment by marcusolsson** [comment]
Alright, I'll fold :) I managed not to see that @leitzler already had submitted a PR to add the "remove all"-functionality. https://github.com/marcusolsson/tui-go/pull/16

**Comment by dougreese** [comment]
I hadn't seen that, either.  I'll still add the `RemoveItem()` method.

**Comment by marcusolsson** [comment]
Thank you!

**Comment by marcusolsson** [comment]
@dougreese Just checking in too see if you're still working on adding that `RemoveItem()`.

**Comment by dougreese** [comment]
I was on vacation for a couple weeks. Today is actually my first day back.  Short answer: yes.

**Comment by marcusolsson** [comment]
Welcome back, I hope your vacation was good :) I'll take a look at it right away!

**Comment by marcusolsson** [comment]
Closed by #22. Thanks!
