### ISSUE TITLE
SetText doesn't work from a different func.

### ISSUE THREAD

**Issue by undeadindustries** [marcusolsson/tui-go#136]
For some reason, SetText on a Label does not work from different files, even if they are global vars in the same package. Something like:

Main.go
package main
MyLabel = tui.NewLabel("doe")
Ui, err = tui.New(tui.NewVBox(MyLabel))
if err := Ui.Run(); err != nil {
	panic(err)
}
MyLabel.SetText("ray")
foo()

other.go

package main
foo() {
MyLabel.SetText("me")
}

go run main.go other.go

MyLabel is still "ray"

I've made all my vars exportable. I'm not sure what I'm doing wrong?

**Comment by marcusolsson** [comment]
The call to ui.Run will block the main goroutine, meaning foo will be run when you exit the application. You'll need to call SetText from another goroutine. Checkout the chat example for some ideas on how you can do this.

**Comment by undeadindustries** [comment]
Now I feel really dumb. I just looked at the chat example and I don't see any go routines?

**Comment by marcusolsson** [comment]
Don't. You're not the first one to ask about it. Actually, I realized that in the chat example the goroutine is managed by the ui. 

You can supply a function to be run every time the user presses enter in the input field.

```
input.OnSubmit(func(e *tui.Entry) {
	history.Append(tui.NewHBox(
		tui.NewLabel(time.Now().Format("15:04")),
		tui.NewPadder(1, 0, tui.NewLabel(fmt.Sprintf("<%s>", "john"))),
		tui.NewLabel(e.Text()),
		tui.NewSpacer(),
	))
	input.SetText("")
})
```

If you want to update the UI from one of your own goroutines, you can use the `ui.Update` method: https://github.com/marcusolsson/tui-go/blob/master/example/audioplayer/main.go#L66-L71

**Comment by undeadindustries** [comment]
Thanks! I'll check it out.
