### ISSUE TITLE
Screen not redrawing with no user input

### ISSUE THREAD

**Issue by dougreese** [marcusolsson/tui-go#15]
I have an application that listens for data and should update the screen when new data is received. Even though widgets are being updated in code, the screen is not redrawn until some user interaction occurs, such as hitting any key on the keyboard.

How can I cause the screen to repaint on new data?  My current workaround is to add a `Repaint()` method to the `UI` interface and `tcellUI` struct, which then calls the Painter.Repaint() method.  It works but feels a bit kludgy, and I have to remember to manually repaint when data is updated. 

Have I missed some functionality that makes this easy?

**Comment by marcusolsson** [comment]
Repaint requests are still work to be done unfortunately. I ran into this issue when I wanted `ProgressBar` to update progress asynchronously (updating progress of a song track). I haven't given this to much thought yet and have no solution in mind at this moment.
