### ISSUE TITLE
Unify text input

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/tui-go#17]
Both `Entry` and `TextEdit` are handling text input. It should be broken out so that work can done to improve text navigation and editing. It would be interesting to see if [readline](https://github.com/chzyer/readline) (or similar) could be used.

**Comment by Danik32** [comment]
Indeed! I was interested in using readline with a console UI library for a while, but I don't think it is possible with any out there. Would be a really nice feature.

**Comment by marcusolsson** [comment]
Agreed. Not sure I'll be able to work on this for a while. If anyone's interested to help out, I'll gladly provide feedback, and help in any way I can.
