### ISSUE TITLE
Wrapping long Label

### ISSUE THREAD

**Issue by yml** [marcusolsson/tui-go#18]
I have been building a [small tui](https://github.com/yml/keep/blob/master/cmd/keep-tui/main.go) on top of my password manager.
The problem I am running is that the notes Label can be longer than there is space on one line. It seems that go-tui truncate the Label. Is there a way to wrap the text and continue the next line ?

May be the root cause is that I should not use [label for notes](https://github.com/yml/keep/blob/master/cmd/keep-tui/main.go#L76). 

![screenshot from 2017-05-22 22-52-01](https://cloud.githubusercontent.com/assets/125902/26327927/663c0fd0-3f41-11e7-8c5a-a484ecb1c271.png)

Thank you very much for releasing go-tui it is very easy to get going.

**Comment by marcusolsson** [comment]
That's really cool! I'm glad to hear you're finding it useful. 

There is some basic support for word wrapping. Check out the `SetWordWrap` method on the `Label` widget. It should do what you're asking for. Let me know if it does the job!

https://github.com/marcusolsson/tui-go/blob/334ee71303bff817c1daaed05707c32c7e7b9f8d/label.go#L66
