### ISSUE TITLE
Help with box sizes

### ISSUE THREAD

**Issue by gonzaloserrano** [marcusolsson/tui-go#31]
Hi there,

I'm working on adding changes against master support to git-br, see https://github.com/gonzaloserrano/git-br/pull/3/commits/0c3f7561cc1c9d210fbf8471c75051daf0d94018#diff-76261312ecc0cc15e62b58b0affe8952R109

What I thought is having a vew similar to this:

```
+----------------------------------+
|----------------------------------|
||date |author| name |-|  changes ||
||     |      |      |-|          ||
||     |      |      |-|          ||
||     |      |      |-|          ||
||     |      |      |-|          ||
||     |      |      |-|          ||
||     |      |      |-|          ||
||     |      |      |-|          ||
||     |      |      |-|          ||
|----------------------------------|
+----------------------------------+
| status line                      |
+----------------------------------+
```

So I tried with a code similar to this:
```go
t := tui.NewTable(0, 0)
t.SetColumnStretch(0, 1)
t.SetColumnStretch(1, 1)
t.SetColumnStretch(2, 2)
for _, br := branches {
    t.AppendRow(/* branches data here */)
}
diffView := tui.NewLabel("")
status := tui.NewStatusBar("")
top := tui.NewHBox(t, diffView)
top.SetSizePolicy(tui.Preferred, tui.Preferred)
root := tui.NewVBox(
    top,
    tui.NewSpacer(),
    status,
)
root.SetSizePolicy(tui.Preferred, tui.Preferred)

// and then

t.OnSelectionChanged(func(t *tui.Table) {
	diffView.SetText(/* string with changes between branches */)
})

```

I'm using `tui.Preferred` everywhere but my result, when the test "overflows" the boxes, is something like this (note the master branch does not have changes against itself):

![output](https://cloud.githubusercontent.com/assets/349328/26764634/922202de-496a-11e7-92f6-06862b2a58b7.gif)

Is there anyway to tell tui that on an horizontal box don't want any resizing? Or should I use a table instead? Ideally I'd want to declare boxes size in a fixed way, lets say 1/7 for the date, 1/7 for author name, 2/7 for branch name and 3/7 for changes, or something similar.

Sorry if this does not make much sense, I'm with hangover :P

**Comment by marcusolsson** [comment]
Your code looks right to me! I'd say you've discovered a bug :) The `Table` widget has been a bit left behind after I redid the layout engine a while back and is due for some refactoring. I'll try to look into this in the coming days! Thanks for reporting!

By the way, widgets are set `tui.Preferred` in both direction by default, so you can safely remove those lines.

**Comment by marcusolsson** [comment]
Please feel free to reopen if the issue still remains.

On your last question regarding declaring proportial sizes for boxes. That's not something that's currently supported and will not likely be added before v1.0.0. Without having tested it first, I believe you should be able to accomplish it by using a `Grid`, with something like this:

```
g := tui.NewGrid(0, 0)
g.AppendRow(table, diffView)
g.SetColumnStretch(0, 4)
g.SetColumnStretch(1, 3)
```

**Comment by gonzaloserrano** [comment]
Thanks! The boxes now render fine.

For now I have decided to skip the table, since I wanted different proportions for columns, and I have used a manual _columnize_ lib that I found somewhere, and switched to `tui.List`, which gives me something like this, that I star to like ;-)

<img width="1280" alt="screenshot 2017-06-06 23 00 02" src="https://user-images.githubusercontent.com/349328/26851778-2bf2180c-4b0c-11e7-8bae-6e5aa8b78668.png">
