### ISSUE TITLE
Callback system or mutex for updates required

### ISSUE THREAD

**Issue by heavenlyhash** [marcusolsson/tui-go#34]
I want to update content based on external events.  For example, I might like to make a dashboard which updates its content every 2 seconds.

To do this, code needs to be able to perform operations on the same goroutine as the rest of the rendering library.  Calling e.g. `SetText` from a key event callback works fine; calling `SetText` from anywhere else after calling `ui.Run` is *a bug*: the race detector will complain loudly and correctly.  (The race detector is *awesome*.)

The 'audioplayer' example demonstrates the issue.  Running `go run -race ./example/audioplayer/main.go` and pressing enter on any of the list items will promptly generate a stream of data race warnings.

Either a mutex of some kind, or, the ability to insert callback functions into a queue is necessary so UI updates can be made without waiting for key/mouse/resize events and without triggering the race detector.  Looking at the queue and select loop already in `ui_tcell.go`, I'd say just extend that: export a method that's roughly like `handleResizeEvent` but accepts a `cb func()`, have it do `ui.eventQueue <- callbackEvent{cb}`, and add a branch to the `handleEvent` switch that responds to a `callbackEvent` by simply running the user's `func()` in the current goroutine.  Races averted!

Related:

- same user story: https://github.com/marcusolsson/tui-go/issues/15

Getting a bit late here, but if that all sounds reasonable I'll write a quick PR tomorrow! :)

**Comment by marcusolsson** [comment]
Closed by #35
