### ISSUE TITLE
setColumnStretch in Grid appears to be unused.

### ISSUE THREAD

**Issue by to-json** [marcusolsson/tui-go#37]
`setColumnStretch` appears to work correctly, setting a stored value, but it does not look to affect rendering at all, and nothing but the setter refers to it. The examples imply it works, or worked. I'm sure you're aware, just wanted to get it onto the issues board.

**Comment by marcusolsson** [comment]
Actually I wasn't aware, so I appreciate you reporting the issue :) Like you say, it's correctly set, but it's value is not being used in the layout calculation. It's likely to have been broken during the last overhaul of the layout engine. Unfortunately, I also see that there aren't any tests for `SetColumnStretch` that would have caught the regression. I will prioritize this one.
