### ISSUE TITLE
Table with overflowing rows

### ISSUE THREAD

**Issue by fenimore** [marcusolsson/tui-go#39]
Hi, What should I do with a table that has too many rows. That is the rows overflow the visible space (or possible space). 

I'm still able to scroll through and select rows outside of view.

Is it possible to detect if a row is outside of view?

I'm using gnome-terminal, 1.8 go and the latest tui-go

**Comment by marcusolsson** [comment]
I'm fairly certain that's not possible at the moment. Ideally, I think there should be some sort of scroll area like [this](http://doc.qt.io/qt-4.8/qscrollarea.html).

**Comment by marcusolsson** [comment]
Created a issue for the scroll feature, #40
