### ISSUE TITLE
Scroll area support

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/tui-go#40]
Tables with too many rows will not fit. When a row outside view is selected the scroll area should offset the view to include the selected row.

For comparison: Qt has a [QScrollArea](http://doc.qt.io/qt-4.8/qscrollarea.html) that decorates a widget with scrolling functionality.

This would be very nice combined with mouse support :)

Example: 

```go
t := tui.NewTable(0,0)
a := tui.NewScrollArea(t)
```

**Comment by fenimore** [comment]
This is kind of an aside, but I've been wondering during my time developing with tui-go, how do you debug/log things? I sometimes use `println` but it prints strangely. 

What is your advice for debugging?

**Comment by marcusolsson** [comment]
I usually call `log.SetOutput` so it outputs to a `debug.log` file. Maybe we could expose it as part of the API?

**Comment by fenimore** [comment]
ah! that seems like a good solution! I'm :+1: for exposing it as part of the `tui-go` api :slightly_smiling_face:

**Comment by lea-anthony** [comment]
I'd very much like to see this widget too 👍

**Comment by marcusolsson** [comment]
@lea-anthony Thanks for showing interest! I have my vacation coming up next week and I plan to be working a lot on tui for a couple of weeks. Knowing what people actually are using makes my priorities much easier. I'll make sure to give this some attention!

**Comment by mifz** [comment]
Any news about scroll area support? II have a huge Label.SetText and can't scroll it.

**Comment by marcusolsson** [comment]
I've been working on this, albeit very slowly, lately. I've run into some unexpected troubles. I've pushed the current state to a `scrollarea` branch in case anyone wants to take a look at it. Try out the `scroll` example. There's some funky stuff going on there right now, and I believe it to be some issues with the clipping mask but I've been unable to find it so far.

**Comment by mifz** [comment]
Anyway, it's working like a charm. ;) 
![untitled](https://user-images.githubusercontent.com/1218279/30421616-ffce8bd8-9945-11e7-8b4b-bd4bfc9610a7.gif)

Thanks!

**Comment by marcusolsson** [comment]
Glad it's working for you! :) The main issues are with scroll areas within nested layouts, and it's something I'd like to figure out before merging to master. Thanks for using tui!

**Comment by cornfeedhobo** [comment]
@mifz could you post that example code somewhere?

**Comment by mifz** [comment]
@cornfeedhobo it's just a couple of simple lines: https://gist.github.com/mifz/08c5fcb242455d1de6256ac29da3c434

**Comment by marcusolsson** [comment]
Thanks for sharing @mifz! I'll make some time this week to hopefully get this one into master!

**Comment by cornfeedhobo** [comment]
@marcusolsson I have been playing with this branch and I came up with a small addition to support fixed scrolling directions. I tried to keep with your patterns, but feel free to adapt as you see fit.
https://github.com/cornfeedhobo/tui-go/blob/scrollarea/scroll_area.go

**Comment by marcusolsson** [comment]
@cornfeedhobo Very nice, I like it! I might redo the current branch a bit, but I'd like to keep your solution in the final version.

**Comment by marcusolsson** [comment]
I think I finally sorted out the issues with this one! I had to redesign the masking strategy a bit so please let me know if it breaks anything for you.
