### ISSUE TITLE
Missing Keybindings

### ISSUE THREAD

**Issue by fenimore** [marcusolsson/tui-go#41]
Hi again!

I've noticed there are some keybindings missing:

- [ ] `"Space"`
- [ ] `"Pause"` https://github.com/gdamore/tcell/blob/master/key.go#L310
- [ ] `"Play" | "Stop" | "Next" | "Previous"`

This list isn't exhaustive, just those which I've come up against

**Comment by marcusolsson** [comment]
Closing with #48
