### ISSUE TITLE
Swapping/Toggling UI components

### ISSUE THREAD

**Issue by lea-anthony** [marcusolsson/tui-go#44]
I'm looking to have 2 different components that can be toggled, where they both occupy the same space (a bit like a tabbed interface would). Is this currently achievable? I didn't notice show/hide methods on widget so assumed not.

**Comment by marcusolsson** [comment]
Hm, no there are currently no preferred way of achieving this, but I definitely think it's something that should be supported. Just to be clear, would you mainly want to use this for toggling views (e.g. tabs) or individual widgets (e.g. show/hide)?

**Comment by lea-anthony** [comment]
Wow, thanks for the quick reply. I think I'd be looking to swap out whole sections like tabs, but just not with the actual tabs if that makes sense. Essentially swap out/in collections of widgets. My actual use case is simple: I have a vbox with 2 widgets, the top widget being the main area whilst the bottom widget is a text input. Depending on what I type, i'd like to swap in/out new 'views' for the top half.

**Comment by marcusolsson** [comment]
I think if we were to add `Show/Hide` or a `SetVisible` to the `Widget` interface, it would also apply to boxes and grids. Then you would be able to add both views to the same box and then simply toggle visibility for each individual `Box`. Would this be helpful?

**Comment by lea-anthony** [comment]
I think that might work. The alternative is to introduce a Z layer for
stacking. This would also help to do dialogs and menus.

**Comment by marcusolsson** [comment]
As a matter of fact, supporting basic compositing is something I've already been giving some thought. Though I think it will involve some discussion around what kind of applications you're going to build with tui-go. Should [overlapping windows](https://github.com/cznic/wm) be supported for example? I don't believe so. I'd like for tui-go to encourage good "terminal UX" and part of that is designed for keyboard-first and support mouse interaction where it makes absolute sense. For example, _drag-and-drop_ functionality is not something I see for tui-go.

With that being said, I believe dialogs and menus are examples of concepts that would fit into that keyboard-first design.

On a side note, I have this idea of border refinement where you would replace ─│─ with ─┼─ in a compositing step where you have things overlapping.

**Comment by HTechHQ** [comment]
I have a related use case where I want to replace one widget inside a box with another one.

So far I introduced a method remove analogous to the insert one and use both in combination to do the replacement.
I propose adding the two new methods:
`(b *Box) Remove(i int)`
`(b *Box) Replace(old, new Widget)`

Let me know what you think and if Box would be the right place to implement this or if something like WidgetBase would be a more appropriate place.

I would be happy to contribute both changes.

**Comment by marcusolsson** [comment]
I think it makes sense to be able to remove a widget from a `Box`. `Replace` on the other hand I'm not so sure about. It should be possible to this accomplish with `Insert`/`Remove`, right?

**Comment by HTechHQ** [comment]
Using ```Remove``` and ```Insert``` in combination will solve the problem, definitely.

The proposed ```Replace``` would be a convenience method for the above steps. 
I see the value in removing cognitive burden while programming. Now you don't have to remember or count the actual position of the widget you are exchanging, but you can use your variable names to identify the widgets instead.

Compare:
```
window.Remove(2)
window.Insert(2, detailBox)
```
with
```
window.Replace(infoBox, detailBox)
```
No strong opinion here. So let me know what you would prefere.

**Comment by marcusolsson** [comment]
Right, my thought is that we probably should avoid convenience methods and helpers in an attempt to keep the API as small as possible. If it's reasonable to create your own helper, I think for now that's the best way to go forward.

**Comment by marcusolsson** [comment]
@lea-anthony Do you think the PR from @HTechHQ would allow us to close this issue?

**Comment by marcusolsson** [comment]
I'm going ahead and closing this issue with #65 but feel free to reopen if needed.
