### ISSUE TITLE
Background colour for HBox

### ISSUE THREAD

**Issue by lea-anthony** [marcusolsson/tui-go#45]
Is there a way I can set a BG colour for an HBox? I'm making a custom status bar using HBox and spacers and whilst it looks good so far, having a background colour would be awesome!

**Comment by marcusolsson** [comment]
I think this is probably what I would expect to get from setting `theme.SetStyle("box", tui.Style{Fg: tui.ColorBlue, Bg: tui.ColorRed)`. This should be a fairly straightforward fix. 

Huge thanks for letting me know what you'd like to see in tui-go!

**Comment by lea-anthony** [comment]
Awesome! Thanks for making a termlib that's easily accessible. I'm going to
study the source this week and see if I can help out in some way.

**Comment by lea-anthony** [comment]
I made a fix for this in my local branch, but after looking at the code, wouldn't it be better to have a custom style defined in WidgetBase that each component uses as an override for default styles?

**Comment by marcusolsson** [comment]
Thanks! Also, super cool that you're interested in contributing to tui-go!

Yes, I think you're right about allowing custom styles for all widgets. Right now, the only widget that supports custom styling is the `Label` widget, using the `SetStyleName` method. I can totally see us moving it up into the `WidgetBase`.
