### ISSUE TITLE
Debugging support

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/tui-go#47]
There should be a way for developers to debug their applications, preferably during runtime.

The way I've been doing is to set `log.SetOutput` to a `debug.log` file. One proposal would be to add a `tui.SetDebug(true)` that would enable this for the current application.

**Comment by d3nw0** [comment]
Maybe a fixed box in the bottom, just like [Firebug](https://getfirebug.com/). It should be activated using `tui.SetDebug(true)`

**Comment by marcusolsson** [comment]
That's a pretty cool idea! It actually combines a few things I'm working on right so it might be a good thing to try out! Kind of want to try this once #46 is implemented to have a HUD that doesn't affect the layout.

**Comment by cceckman** [comment]
I'd be wary of putting a HUD within tui itself, basically from a [Heisenbergian](https://en.wikipedia.org/wiki/Uncertainty_principle) perspective: if what you're logging is UI events, and logging them generates UI events, you've just created a recipe for deadlock or an infinite loop. Or, if you're explicitly ignoring events going to the log panel... then you're missing some of the events your system is handling, and therefore your debugging is incomplete.

That said - I can imagine two useful things that would still allow that behavior. :-)

- Add a UI method `SetLogger(log.Logger)`, which registers a handler for the UI to write to. The user of `tui` would need to set this up to log to whatever output they want - file, web handler, etc., whatever. This obviates the need for a `SetDebug` method - log if the logger is set, don't log if it isn't. I think this is the main request for 'debugging support'.

- Add a new `Widget` that implements `log.Logger`, printing out the logged events. This could be used as a debug panel for `tui` (though see my concerns in the first paragraph), but could be used as a log sink for anything else that takes a `log.Logger`.
