### ISSUE TITLE
Problems with Go 1.9

### ISSUE THREAD

**Issue by mifz** [marcusolsson/tui-go#50]
Hello,

I have a problems with TUI and Go 1.9. For example:

OS: Debian Jessie (8.9) or Ubuntu 16.04.2 LTS

Sample from README.md:

```
package main

import "github.com/marcusolsson/tui-go"

func main() {
	box := tui.NewVBox(
		tui.NewLabel("tui-go"),
	)

	ui := tui.New(box)
	ui.SetKeybinding("Esc", func() { ui.Quit() })

	if err := ui.Run(); err != nil {
		panic(err)
	}
}
```

Result: 

Go 1.8.3 - Esc works
Go 1.9 - Esc not works

Next i replaced Esc with F10:

Go 1.8.3 - F10 - works
Go 1.9 - F10 - works, but hangs after the interface is cleaned up - i press Enter.

**Comment by marcusolsson** [comment]
Hm, might be an issue with tcell. Will take a look at it later tonight! Thanks for reporting!

**Comment by marcusolsson** [comment]
Not seeing this on my MacBook, but I'll make sure to try out on my Linux machine as well. If you've updated to 1.9 recently, I think it might help to run `go get -u ./...` to make sure tcell is built with 1.9 as well.

**Comment by mifz** [comment]
Yes, i have no problems on my Macbook with 1.9 also, only Linux.

**Comment by cornfeedhobo** [comment]
Confirming. Linux here.

**Comment by marcusolsson** [comment]
@cornfeedhobo I've confirmed as well. Tried running the tcell demos and seeing the same thing so indeed looks like a tcell issue. I've reported the issue [here](https://github.com/gdamore/tcell/issues/164).

**Comment by marcusolsson** [comment]
Closing, but feel free to reopen if you're still seeing this.
