### ISSUE TITLE
Scrolling between text (Entry, TextEdit) with right and left cursor

### ISSUE THREAD

**Issue by mifz** [marcusolsson/tui-go#51]
Hello,

Subj. :) 

For example, i have a huge password like: "@#oiudsJKYdbsjH2" with mistake somewhere in the middle. I need to delete all characters until mistake in the string.

**Comment by marcusolsson** [comment]
A very reasonable request :) I think this is fairly straightforward to implement, in case someone wants to go at it.

`tui.Entry` would likely need to keep a cursor position and then listen to KeyLeft and KeyRight events here:

https://github.com/marcusolsson/tui-go/blob/master/entry.go#L68-L80
