### ISSUE TITLE
Why is q the default to quit?

### ISSUE THREAD

**Issue by lostinblue** [marcusolsson/tui-go#6]
In the chat application you can not type any message with the letter q. Should all keystrokes not be manually set?

**Comment by marcusolsson** [comment]
You're absolutely right. Due to the current lack of proper event handling it's set to 'q' and Esc for convenience during early development.

Unfortunately, development has been stalled due to a new job and my laptop being stolen, but I will make sure to take a look at this in the coming days.

Thank you for your interest in tui!

**Comment by lostinblue** [comment]
Sorry to hear about your laptop, but good to hear you found a new position. 

This is a nice convenience library for rapid prototyping of a tui. Thanks for letting me know the state of the project. If I can manage to figure it out and come up with a way of assigning keys that fits the lib I will send a pull request.

**Comment by lostinblue** [comment]
For now would the best way to handle this and still use the library to just override that original assignment? It may be worth adding to the chat example if I can figure it out.

**Comment by marcusolsson** [comment]
Thanks! I'm actually working on a commit at the moment, but I'd love to
accept your PR. I'll push my branch tomorrow so you can have a look.

Den sön 8 jan. 2017 23:11x <notifications@github.com> skrev:

**Comment by marcusolsson** [comment]
Here's a prototype that's inspired by the way [gocui](https://github.com/jroimartin/gocui) does it: https://github.com/marcusolsson/tui-go/commit/3471cd8cefb598d335de6c719924468859133e0c An alternative to type switching on the empty interface I guess would be to parse a string, e.g. "Esc", "q" or even "C-x". Looking forward to see your idea on how to solve it!

**Comment by marcusolsson** [comment]
I'm closing this but feel free to suggest any improvements to the current approach.
