### ISSUE TITLE
support chinese text

### ISSUE THREAD

**Issue by Chyroc** [marcusolsson/tui-go#64]
see this:https://travis-ci.org/marcusolsson/tui-go/jobs/300122241#L542-L555

width bigger than 1 well failed

**Comment by marcusolsson** [comment]
I'm currently working on improved text support and I will see if I can look at this once it's a bit more robust! Thanks for the heads up!

**Comment by marcusolsson** [comment]
There's likely more to be done to improve support for wide characters. For example, I noticed that the cursor doesn't really cover the whole of the character unfortunately.

<img width="84" alt="skarmavbild 2017-11-25 kl 10 39 34" src="https://user-images.githubusercontent.com/8396880/33229341-3c682e9a-d1cd-11e7-9e29-7eb4890d6085.png">

If you find any more problems related, please feel free to create additional issues! Thanks!
