### ISSUE TITLE
Make testSurface public

### ISSUE THREAD

**Issue by cceckman** [marcusolsson/tui-go#66]
painter_test.go has a nice implementation of the Surface interface for testing writes.

It would be nice to factor that out so tui users can test their own layouts or custom Widgets.

**Comment by cceckman** [comment]
I apparently don't have permission to assign this to myself, but happy to take it on. :-)

**Comment by cceckman** [comment]
Grah. First though was "put it in its own subpackage", but that doesn't work because the tests are in the same package as the main code- which means that there's an import cycle (the test cell requires `tui.Style`, and then tests use the test surface.)

If repackaging were carried through - making `Style` its own package (and maybe `Theme`), that would work... but that's a big / disruptive step to take for this FR.

Another option would be to provide the test surface as a subpackage, but not to use it for the actual tests. That seems like a bad idea- want to keep the features, bugs, etc. in sync.

Another-other option would be making `Style` an interface, which the current `tui.Style` struct implements, and which the testing package implements on its own.

But...yeah, this isn't as simple as I'd thought. -.-

**Comment by cceckman** [comment]
Or, the simplest but least pretty option: put `TestSurface` in the `tui` package, as `testsurface.go` rather than a `_test.go` file - i.e. just export it.

**Comment by cceckman** [comment]
Oh, nice - I missed that it's not just Bazel that lets you put _test files into a _test package; Go itself allows it too. Oddly, I'm not seeing that in the official documentation, but a quick search shows at least [a couple](https://medium.com/@matryer/5-simple-tips-and-tricks-for-writing-unit-tests-in-golang-619653f90742) [docs](https://medium.com/@benbjohnson/structuring-tests-in-go-46ddee7a25c) giving advice advocate for it.

I'm an advocate of that too, so, will do that first.

**Comment by marcusolsson** [comment]
Awesome to see you jumping in! I'm aware of the `_test` package and why it's a good thing, and I don't see any issues with adopting it (apart from making the `Offset` field public, but we can probably live with that). However, I don't see how it would solve the problem of making `testSurface` public?

I actually don't think making `TestSurface` part of the `tui` package is that bad. There are even a few articles mentioning this pattern (check Trick 6 on https://medium.com/@povilasve/go-advanced-tips-tricks-a872503ac859). I think moving TestSurface into a `testing.go` makes sense.

**Comment by marcusolsson** [comment]
Regarding testing styles, I've had this idea of using https://github.com/fatih/color in the TestSurface for a nice test output when developing. Haven't tested it so not sure if feasible or worth it though :)

**Comment by cceckman** [comment]
`_test` on its own doesn't allow `testSurface` to be public- it allows it to be in a different package than `tui`. That isn't the only way to make it public- it's just my preference to keep test helpers in separate packages. (For comparison, Bazel has the notion of [`testonly`](https://docs.bazel.build/versions/master/be/common-definitions.html#testonly) packages; that isn't in mainline Go, but I think the separation is useful regardless.) 

Adding actual-color to `testSurface` would be cool- I might look at that in publicizing TestSurface. I'm a little worried that adding another layer / type of mapping for color may make things more confusing rather than less... prettier output, yes, but it's also possible that a single color index ("default") might map to more than one output (#ffffff), or vice versa. I guess annotating the color index (0) with the rendered color (e.g. &lt;colorcode&gt;0&lt;/colorcode&gt;) would make it nicer to read but also be explicit about what's going on.

**Comment by cceckman** [comment]
Per comment on #67  - I'll just do as per the [above comment](#issuecomment-343718043), and publicize as `tui.TestSurface` without adding a separate package. Too many merge conflicts / current tests that test internal state.
