### ISSUE TITLE
Example of coloring?

### ISSUE THREAD

**Issue by lostinblue** [marcusolsson/tui-go#7]
Is there an example anywhere of how you setup coloring? Is painter meant to be used for just general text coloring?

**Comment by marcusolsson** [comment]
Painter is used for more low-level drawing. There's some early theming support through `Palette`. There's more work to be done here, but the idea is to, in the future, be able to share color schemes across applications written in tui-go.

Currently, some of the widgets define style identifiers that you can specify foreground and background colors for. 

Here's an example:

```go
p := tui.NewPalette()
p.SetItem("table.cell.selected", tui.PaletteItem{
    Bg: tui.Color(termbox.Black),
    Fg: tui.Color(termbox.Red),
})

ui := tui.New()
ui.SetPalette(p)
```

You'll find the identifiers for the widgets in their respective `Draw` function. I'd be happy to hear your feedback.
