### ISSUE TITLE
Responsive widget component

### ISSUE THREAD

**Issue by taylorchu** [marcusolsson/tui-go#73]
To be responsive, the widget will need to have a background goroutine to handle tasks from the '.OnXXX' handler, because the ui will block if those handlers are doing time-consuming work.

This makes designing widget component difficult because tui.UI.Update is not available in the scope for safely updating the view after the work is finished in the background goroutine.

There should be some guide/example to make this easier.

**Comment by marcusolsson** [comment]
I was expecting the day this would become an issue :) I'd love to use this issue to figure out the best way to implement this. 

Right now, the widgets are unaware of the UI and ideally I'd like to keep it that way, but maybe the WidgetBase could have a

```go
type RepaintRequester interface {
    RequestRepaint()
}
```

as a field or something similar? What do you think?

**Comment by taylorchu** [comment]
Won't this be a data race if we modify the widget while tui is currently reading those widgets for repainting?

**Comment by marcusolsson** [comment]
Probably. I'll have to do some reading before I take this on. Thanks for bringing it up though!

**Comment by cceckman** [comment]
I'm interested in this feature as well- can we re-open?

A couple of cases I'm thinking of are, I think, basically HTML's inline layout mode:

- `<span>`-style markup within themes. Currently, the only way to theme a selection of text would be to have adjacent `Label`s with different styles assigned; that would work OK for a single line of text, but wouldn't allow wrapping. (Wrapping gets more complicated in that case anyway, but...)
- Row/Column layouts: displaying N items, each of a known size, that I'd like to either stack-and-overflow-to-a-column, or lay out side-by-side-with-overflow-to-a-row.
