### ISSUE TITLE
reading from entry field

### ISSUE THREAD

**Issue by raghuvanshy** [marcusolsson/tui-go#75]
Ola good ppl of tui-go,
first of all this library is awesome and working with it is both educational and fun.

Crux of the matter:
while developing an cli application where we want the user to enter a command/run a script via the application. This is stright forward in go and works great. but when it comes to me trying make a tui for it im stuck.
for example in my code below I am writing data to a pipe and using its reader end to collect user input from the cli. When user is in the tui my super pretty ui freezes.
[stackoverflow issue for the same](
https://stackoverflow.com/questions/47586352/tui-go-entry-pipe-golang)

any and all advice is appreciated.

```
func main() {
    // forces user to tui
    // isTui := false
    isTui := true

    if isTui {
        welcome()

    } else {
        // cli mode works
        pr, pw, _ := os.Pipe()
        var nilGrid *tui.Grid
        go askYesNo("shall we test", false, pr, pw, nilGrid)
        io.Copy(os.Stdout, pr)
    }

}

func welcome() {
    pr, pw, _ := os.Pipe()
    grid := tui.NewGrid(0, 0)
    //var tStr string

    window := tui.NewVBox(
        tui.NewPadder(13, 1, tui.NewLabel("testing")),
        tui.NewPadder(13, 1, grid),
    )

    // is able to attach the entry field to the grid
    //go askYesNo("shall we test", true, pr, pw, grid)

    ui := tui.New(window)
    ui.SetKeybinding("Esc", func() { ui.Quit() })
    ui.Run()

    buf := new(bytes.Buffer)
    w := bufio.NewWriter(buf)
    defer w.Flush()

    // Calling askYesNo func here does not attach the entry fiels to the grid
    go askYesNo("shall we test", true, pr, pw, grid)
    if _, err := io.Copy(w, pr); err == nil {
        fmt.Println(buf.String())
        grid.AppendRow(
            tui.NewLabel("test AppendRow"),
            tui.NewLabel(buf.String()),
        )
    }

}

func askYesNo(text string, isTui bool, pr *os.File, pw *os.File, grid *tui.Grid) {
    // writes current time to pipe
    fmt.Fprintln(pw, time.Now().Format(time.UnixDate)+text+"?(y/n)")

    if isTui {

        // attaches entry to screen
        in := tui.NewEntry()
        grid.AppendRow(
            in,
        )

        grid.SetBorder(true)
        in.SetFocused(true)

        // Collects user entry and responds
        in.OnSubmit(func(en *tui.Entry) {
            // would prefer to close after this submition has been recorded
            // sadly this also leaves an open pipe thus the program is parallelized
            defer pw.Close()

            fmt.Fprint(pw, time.Now().Format(time.UnixDate)+en.Text())
            in.SetFocused(false)
        })

        fmt.Fprintln(pw, time.Now().Format(time.UnixDate)+" hello world")
    } else {
        pr = os.Stdin
        scanner := bufio.NewScanner(pr)
        scanner.Scan()
        fmt.Fprint(pw, "from pipe "+scanner.Text())
    }
}
```

**Comment by marcusolsson** [comment]
I replied to this on [Twitter](https://twitter.com/marcusolsson/status/936512466800009216), but basically, the `ui.Run()` will block until user presses Esc, which means that everything that follows it will run once the UI has been stopped.

I think you'd probably want to construct the whole UI first, and then run it. If you do that, I don't think you need to call the askYesNo when using the tui.

Would something like this work for you?:

```go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"

	tui "github.com/marcusolsson/tui-go"
)

func main() {
	var out bytes.Buffer

	isTui := true

	if isTui {
		runUI(&out)
	} else {
		runCLI(&out)
	}

	fmt.Println(out.String())
}

func runUI(w io.Writer) error {
	grid := tui.NewGrid(0, 0)
	grid.SetBorder(true)

	window := tui.NewVBox(
		tui.NewPadder(13, 1, tui.NewLabel("testing")),
		tui.NewPadder(13, 1, grid),
	)

	ui := tui.New(window)
	ui.SetKeybinding("Esc", func() { ui.Quit() })

	in := tui.NewEntry()
	in.SetFocused(true)
	in.SetFocused(true)
	in.OnSubmit(func(e *tui.Entry) {
		fmt.Fprintf(w, "You said (with UI): %q", e.Text())
		ui.Quit()
	})

	grid.AppendRow(in)

	return ui.Run()
}

func runCLI(w io.Writer) {
	fmt.Println("Enter your input:")
	scanner := bufio.NewScanner(os.Stdin)
	scanner.Scan()
	fmt.Fprintf(w, "You said (with CLI): %q", scanner.Text())
}
```

**Comment by marcusolsson** [comment]
@raghuvanshy I'm going ahead a closing this, but feel free to reopen it should it still be an issue.

**Comment by raghuvanshy** [comment]
Hello Marcus,
thank you for your input, it helped in guiding me towards using ui.Run() as a blocking statement and generating content for the grid using goroutines.
in doing so ive come across a tcell bug from the looks of it:

    panic: close of closed channel

    goroutine 1 [running]:
    github.com/gdamore/tcell.(*tScreen).Fini(0xc420078340)
        /home/coderiot/go/src/github.com/gdamore/tcell/tscreen.go:399 +0x1f2
    github.com/marcusolsson/tui-go.(*tcellUI).Quit(0xc42005cc60)
    /home/coderiot/go/src/github.com/marcusolsson/tui-go/ui_tcell.go:142 +0x34 
    main.buildUI(0xc4203ed920, 0xa0a218, 0xc42007c280, 0x9d4e40, 0xc42005cc60, 0xc4203dcc88, 0x1)
    /home/coderiot/go/src/github.com/networkinss/go/don/runUi.go:44 +0x554
    main.newDataScreen(0xc42007c280, 0x0, 0x0, 0x9d4e40, 0xc42005cc60)
    /home/coderiot/go/src/github.com/networkinss/go/don/newDataScreen.go:14 +0x3f7
    main.setMenuKeybindings.func2.1()
    /home/coderiot/go/src/github.com/networkinss/go/don/setKeybindings.go:27 +0x7d
    github.com/marcusolsson/tui-go.(*tcellUI).handleEvent(0xc42005cc60, 0x7d72c0, 0xc4203dc890)
    /home/coderiot/go/src/github.com/marcusolsson/tui-go/ui_tcell.go:109 +0x137
    github.com/marcusolsson/tui-go.(*tcellUI).Run(0xc42005cc60, 0xc420174910, 0x7525a6)
    /home/coderiot/go/src/github.com/marcusolsson/tui-go/ui_tcell.go:99 +0x136
    main.runUI(0x9d4e40, 0xc42005cc60)
    /home/coderiot/go/src/github.com/networkinss/go/don/runUi.go:57 +0x31
    main.newDataScreen(0xc42007c280, 0x0, 0x0, 0x9d4e40, 0xc42005cc60)
    /home/coderiot/go/src/github.com/networkinss/go/don/newDataScreen.go:21 +0x4f4 
    main.setMenuKeybindings.func2.1()
    /home/coderiot/go/src/github.com/networkinss/go/don/setKeybindings.go:27 +0x7d
    github.com/marcusolsson/tui-go.(*tcellUI).handleEvent(0xc4203ec660, 0x7d72c0, 0xc4203724f0)
    /home/coderiot/go/src/github.com/marcusolsson/tui-go/ui_tcell.go:109 +0x137
    github.com/marcusolsson/tui-go.(*tcellUI).Run(0xc4203ec660, 0xc4202a4b70, 0xc4202a4b40)
    /home/coderiot/go/src/github.com/marcusolsson/tui-go/ui_tcell.go:99 +0x136 
    main.runUI(0x9d4e40, 0xc4203ec660)
    /home/coderiot/go/src/github.com/networkinss/go/don/runUi.go:57 +0x31
    main.welcome(0xc420014045, 0x5, 0x81ba55, 0x6, 0xc4200184c0, 0x1d, 0x1, 0xc420016390, 0x26)
    /home/coderiot/go/src/github.com/networkinss/go/don/welcome.go:96 +0x97c
    main.main()
    /home/coderiot/go/src/github.com/networkinss/go/don/main.go:266 +0x40cd

From the previous post you can see im trying to pipe text and collect data from the tui onto a pipe. for the most part I have managed this. the error is sporadic. is this a go 1.9 issue?

Note have reinstalled tui-go and the error persists.
