### ISSUE TITLE
Chinese is cut off in the table column when the table is in the scrollArea

### ISSUE THREAD

**Issue by mikunalpha** [marcusolsson/tui-go#76]
![screenshot from 2017-12-06 14-33-20](https://user-images.githubusercontent.com/7397397/33648099-3cb82200-da93-11e7-85dc-3844fd8b9d23.png)

```go
package main

import (
	tui "github.com/marcusolsson/tui-go"
)

func main() {
	table := tui.NewTable(0, 0)
	for i := 0; i < 10; i++ {
		table.AppendRow(
			tui.NewLabel("1234"),
			tui.NewLabel("你好謝謝你"),
			tui.NewLabel("4321"),
		)
	}

	scrollArea := tui.NewScrollArea(table)

	container := tui.NewVBox(scrollArea)
	container.SetBorder(true)
	container.SetSizePolicy(tui.Expanding, tui.Expanding)

	ui := tui.New(container)
	ui.SetKeybinding("Esc", func() { ui.Quit() })
	ui.Run()
}
```

**Comment by mikunalpha** [comment]
A workaround to this, change `s := dim(a, w.MinSizeHint())` to `s := dim(a, w.SizeHint())` at
https://github.com/marcusolsson/tui-go/blob/master/grid.go#L207

**Comment by marcusolsson** [comment]
This issue is not limited to CJK languages, but is related to how the size hint (optimal size) is calculated. #121 fixes this. Thanks for reporting!
