### ISSUE TITLE
Use the scan gun to enter, the obtained character is missing or disordered

### ISSUE THREAD

**Issue by fifsky** [marcusolsson/tui-go#77]
```
urlEntry := tui.NewEntry()
urlEntry.OnSubmit(func(e *tui.Entry) {
	respBodyLbl.SetText(e.Text())
})
```

I wrote a simple example, but i use scan gun to enter, `e.Text()` get the data is error

Such as，
barcode context is `134676256887129983`

`e.Text()` get the `1346762568871`, missing `29983`

Maybe it's because the scan gun is too fast, Goroutine is not sequential, When the scan gun input Enter char, It's triggered in advance OnSubmit

**Comment by marcusolsson** [comment]
Sorry for the late reply. I have no experience of scan guns but it sounds like a really cool application! Have you made sure you're getting all the numbers from the scan gun? It might also be that the last numbers are masked away since the Box it's in is too small maybe?

**Comment by marcusolsson** [comment]
Feel free to reopen if the problem persists
