### ISSUE TITLE
Proposal: partial application of Style

### ISSUE THREAD

**Issue by cceckman** [marcusolsson/tui-go#81]
Currently, Styles are all-or-nothing. If `WithStyle` applies a style, it applies all of the fields from that `Style`. 

This means that there's no way to partially apply a style- e.g. to say "I want to be just like the thing that's currently applied, but reversed."

Proposal: the default (zero) value of a `Style` means "inherit everything from whatever is currently applied". At the root of rendering, that's just the terminal's defaults; but it means that e.g. an underlined `Label` or reversed `Button` could keep the colors of its parent `Box`, just with that one transform.

This was discussed in #74, but also facilitates patterns along the lines of #36 : e.g. a `Button` has a base style, but also gets the `reversed` style on top of that when focused.

**Comment by marcusolsson** [comment]
I like it and I'm inclined to give it a shot! It would be great if we could demonstrate this in the color example maybe?
