### ISSUE TITLE
Request: True color support

### ISSUE THREAD

**Issue by d3nw0** [marcusolsson/tui-go#93]
I'm making an application and i need true color support, I have tried setting the color to this:
`t.SetStyle("list.item", ui.Style{Fg: (r+g+b)/3, Bold: 1})`

But that doesn't seem to work. Any ideas?

**Comment by cceckman** [comment]
It looks like the underlying `tcell` library [does support true color](https://github.com/gdamore/tcell#24-bit-color).

**Comment by marcusolsson** [comment]
Yes, `tcell` supports true colors, although if I remember correctly, termbox doesn't (which I started out with). It should be fairly straightforward to extend the API.

**Comment by d3nw0** [comment]
I made some changes to the code. Check #95
